name: Run
on:
  workflow_dispatch:
    inputs:
      DATE:
        description: "Override Date"
  schedule:
    - cron: "0 1 1 * *"
jobs:
  sling:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      PROJECT_ID: 12310710
      PROJECT_NAME: SLING
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm install
      - run: node .
        env:
          DATE: ${{ github.event.inputs.DATE }}
          JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
          JIRA_PASSWORD: ${{ secrets.JIRA_PASSWORD }}
      - uses: actions/upload-artifact@v2
        if: ${{ cancelled() || failure() }}
        with:
          name: error.pdf
          path: dist/error.pdf
      - uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{secrets.MAIL_HOST}}
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          from: ${{secrets.MAIL_SENDER}}
          to: ${{secrets.MAIL_SENDER}}
          password: ${{secrets.MAIL_PASSWORD}}
          secure: true
          html_body: file://./dist/releases.html
          subject: Apache Sling Releases Last Month
          bcc: daniel.klco@gmail.com
          body: Latest Sling Release information generated!
  felix:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      PROJECT_ID: 12310100
      PROJECT_NAME: FELIX
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm install
      - run: node .
        env:
          DATE: ${{ github.event.inputs.DATE }}
          JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
          JIRA_PASSWORD: ${{ secrets.JIRA_PASSWORD }}
      - uses: actions/upload-artifact@v2
        if: ${{ cancelled() || failure() }}
        with:
          name: error.pdf
          path: dist/error.pdf
      - uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{secrets.MAIL_HOST}}
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          from: ${{secrets.MAIL_SENDER}}
          to: ${{secrets.MAIL_SENDER}}
          password: ${{secrets.MAIL_PASSWORD}}
          secure: true
          html_body: file://./dist/releases.html
          subject: Apache Felix Releases Last Month
          bcc: daniel.klco@gmail.com
          body: Latest Felix Release information generated!
  oak:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      PROJECT_ID: 12313221
      PROJECT_NAME: OAK
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm install
      - run: node .
        env:
          DATE: ${{ github.event.inputs.DATE }}
          JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
          JIRA_PASSWORD: ${{ secrets.JIRA_PASSWORD }}
      - uses: actions/upload-artifact@v2
        if: ${{ cancelled() || failure() }}
        with:
          name: error.pdf
          path: dist/error.pdf
      - uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{secrets.MAIL_HOST}}
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          from: ${{secrets.MAIL_SENDER}}
          to: ${{secrets.MAIL_SENDER}}
          password: ${{secrets.MAIL_PASSWORD}}
          secure: true
          html_body: file://./dist/releases.html
          subject: Apache Felix Releases Last Month
          bcc: daniel.klco@gmail.com
          body: Latest Felix Release information generated!
