name: Run
on:
  workflow_dispatch:
    inputs:
      DATE:
        description: "Override Date"
  schedule:
    - cron: "0 1 1 * *"
jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm install
      - run: node .
        env:
          CMS_HOST: ${{ secrets.CMS_HOST }}
          CMS_USERNAME: ${{ secrets.CMS_USERNAME }}
          CMS_PASSWORD: ${{ secrets.CMS_PASSWORD }}
          DATE: ${{ github.event.inputs.DATE }}
          JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
          JIRA_PASSWORD: ${{ secrets.JIRA_PASSWORD }}
          PUPPETEER_UA: ${{ secrets.PUPPETEER_UA }}
      - uses: actions/upload-artifact@v2
        if: ${{ cancelled() || failure() }}
        with:
          name: error.pdf
          path: dist/error.pdf
      - uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{secrets.MAIL_HOST}}
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          from: ${{secrets.MAIL_SENDER}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Sling Relase Info Posted
          to: ${{secrets.MAIL_RECIPIENT}}
          secure: true
          body: Latest Sling Release information generated!
          attachments: ./dist/releases.html
