name: Run
on:
  workflow_dispatch:
    inputs:
      DATE:
        description: "Override Date"
  schedule:
    - cron: "0 1 1 * *"
jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm install
      - run: node .
        env:
          JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
          JIRA_PASSWORD: ${{ secrets.JIRA_PASSWORD }}
          DATE: ${{ github.event.inputs.DATE }}
          CMS_HOST: ${{ secrets.CMS_HOST }}
          CMS_USERNAME: ${{ secrets.CMS_USERNAME }}
          CMS_PASSWORD: ${{ secrets.CMS_PASSWORD }}
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: error.png
          path: dist/error.png
      - uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{secrets.MAIL_HOST}}
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Sling Relase Info Posted
          to: ${{secrets.MAIL_RECIPIENT}}
          secure: true
          body: Latest Sling Release info updated at ${{ secrets.CMS_HOST }}/cms/site/content.html${{secrets.CMS_SITE_PATH}}/posts
